version: '3.1'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - uploads:/usr/app/uploads
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    # env-file: ".env"
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_DB: courses
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
    driver: local
  uploads: