version: '3'
services:
  web:
    build: .
    command: npm run dev
    networks:
      - mynetwork
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    # env-file: ".env"
  postgres:
    image: postgres:latest
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: courses
      POSTGRES_PASSWORD: root

networks:
  mynetwork:
    driver: bridge